### ISSUE TITLE
Whole bunch of diff code in the source

### ISSUE THREAD

**Issue by andrewfenn** [wgois/OIS#17]
Example: https://github.com/wgois/OIS/blob/master/demos/OISConsole.cpp#L1

Seems like a bad merge has left Diff code in the master branch?

**Comment by azmeuk** [comment]
@TheOnlyJoey  @hymerman Last commit is 6 months old, and the code is invalid since. Previous commits are 3 years old. The team seem to not have time to handle this, this is understandable, it happens. Maybe it is time to let some more people get involved in the project so they can handle waiting pull requests, and make the project live again?

**Comment by Ybalrid** [comment]
Hi guys, I merged your changes. I'm going to take some time to get this project back on track ;-)
