### ISSUE TITLE
Linux non-exclusive mouse capture problem

### ISSUE THREAD

**Issue by Ybalrid** [wgois/OIS#36]
Here's a better place to discuss problem raised by @VisualEntertainmentAndTechnologies on some linux DE. For reference, see discussion on PR #13

**Comment by Ybalrid** [comment]
@VisualEntertainmentAndTechnologies So, I've just pushed a change to master that increase the margins form 5 to 100 as you did in your original PR #13.

Would you be able to validate them ? 

(for reference, this is commit 9c844390326a4e8e55575f48a3ba23853922f478)

**Comment by VisualEntertainmentAndTechnologies** [comment]
Was able to compile it and throw it in a test build for my project. Warping issues are not present with Ubuntu and Unity. So I can confirm 

I also dug through my files and found a demo that the warping issues is present in if you wanted to see it. But I guess it shouldn't matter since this clears up the issue.

**Comment by Ybalrid** [comment]
Great, so we are done with this one ;-)
